### ISSUE TITLE
Compiling with Visual Studio

### ISSUE THREAD

**Issue by wo80** [starseeker/SuperLU#2]
Compiling the static library with Visual Studio works well, but most of the example programs and the tests won't build, because on Windows we don't have `getopt`.

To fix this without touching the SuperLU code I included the files from https://github.com/alex85k/wingetopt (using `if(MSVC)` in the cmake files).

Should I create a pull request?

**Comment by starseeker** [comment]
Sure - sounds good.  Thanks!

**Comment by starseeker** [comment]
pull request applied - thanks!
